version: '3.8'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:latest
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: pyscbist/yamdb-final:latest
    volumes:
      - staticfiles:/code/static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.6
    volumes:
      - staticfiles:/static
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
    depends_on:
      - app
